### ISSUE TITLE
api/posts?status=pending not working unless a moderator is specified

### ISSUE THREAD

**Issue by espoem** [utopian-io/api.utopian.io#100]
### Expected behaviour

Calling `https://api.utopian.io/api/posts?status=pending` should retrieve posts with the flag `pending == true`.

### Actual behaviour

Pending posts can be retrieved only if a moderator is specified or section == author and author is defined.

`https://api.utopian.io/api/posts?status=pending&moderator=moderator`
`https://api.utopian.io/api/posts?status=pending&section=author&author=account`

If the moderator is not set, then the query includes both `'json_metadata.moderator.reviewed': true,` and `'json_metadata.moderator.pending': true,`

Related code:

- https://github.com/utopian-io/api.utopian.io/blob/master/src/server/controllers/post.controller/index.ts#L294
- https://github.com/utopian-io/api.utopian.io/blob/master/src/server/controllers/post.controller/index.ts#L340

**Comment by wehmoen** [comment]
This is not a bug. Its the intended behaiviour.
