### ISSUE TITLE
Wrong points calculation for moderator payout

### ISSUE THREAD

**Issue by mktcode** [utopian-io/api.utopian.io#82]
https://github.com/utopian-io/api.utopian.io/blob/master/src/utopian-pay.ts#L26

![image](https://user-images.githubusercontent.com/6792578/35942007-92acdff0-0c54-11e8-9f68-f7bc9d3518d3.png)

Shouldn't it be 56 points?

**Comment by espoem** [comment]
The points are based on weights in https://github.com/utopian-io/api.utopian.io/blob/master/src/utopian-mod-pay/index.ts

**Comment by mktcode** [comment]
I forgot.... :P
