### ISSUE TITLE
Should I follow git-flow while contributing?

### ISSUE THREAD

**Issue by hernandev** [utopian-io/api.utopian.io#86]
So, I just cloned this to contribute on the project, but the `master` has more recent comments than `develop` branch, so I have the question about which branch should receive pull requests.

Thank you all.

**Comment by eastmaels** [comment]
It should be develop if it's a function change. Reviewer will merge develop to master when it's ok. Recent changes to master I believe are related with rule changes.

**Comment by wehmoen** [comment]
Senn Pull Requests only to the develeopment branch
